# Generated by Django 6.1 on 2026-08-23 06:56

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('linkedin_url', models.URLField(blank=True)),
                ('field_tag', models.CharField(blank=True, help_text="Guest's industry/field, shown on their public profile.", max_length=30)),
                ('phone', models.CharField(blank=True, help_text='Optional. Not verified for MVP — shown as unverified to the other party.', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, e.g. +971501234567.', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('phone_verified', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('general_area', models.CharField(help_text="Public-facing approximate area, e.g. 'JBR, Dubai'.", max_length=120)),
                ('exact_address', models.CharField(help_text='Only surfaced to guests with an ACCEPTED booking.', max_length=255)),
                ('location_url', models.URLField(blank=True, help_text='Optional link to Google Maps or similar.')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('seats_total', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('field_tag', models.CharField(choices=[('tech', 'Tech'), ('design', 'Design'), ('mechanical', 'Mechanical'), ('general', 'General / Mixed')], max_length=20)),
                ('women_only', models.BooleanField(default=False, help_text='If True, listing is restricted to female guests only.')),
                ('is_free', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Null/blank when is_free=True.', max_digits=8, null=True)),
                ('kid_friendly', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('lunch_included', models.BooleanField(default=False)),
                ('wifi_available', models.BooleanField(default=False)),
                ('wifi_speed_mbps', models.PositiveIntegerField(blank=True, null=True)),
                ('parking_available', models.BooleanField(default=False)),
                ('quiet_room', models.BooleanField(default=False)),
                ('house_rules', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, help_text='Optional note guest sends with the request.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_made', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='spaceshare.listing')),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_photos/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='spaceshare.listing')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['date', 'status'], name='spaceshare__date_9aa8f2_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['field_tag'], name='spaceshare__field_t_9a1bbd_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_free', True), ('price__isnull', True)), models.Q(('is_free', False), ('price__isnull', False)), _connector='OR'), name='price_matches_is_free'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='end_time_after_start_time'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted'])), fields=('listing', 'guest'), name='unique_active_booking_per_guest_per_listing'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('responded_at__isnull', True), ('responded_at__gte', models.F('booked_at')), _connector='OR'), name='responded_after_booked'),
        ),
    ]
