# Generated by Django 6.1 on 2026-08-25 04:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceshare', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cover_image',
            field=models.URLField(blank=True, help_text='Stock or uploaded cover photo URL shown on browse/detail. Separate from ListingPhoto, which is for multi-photo galleries.'),
        ),
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Same privacy gating as exact_address.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Same privacy gating as exact_address.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='prayer_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(blank=True, help_text="User's general area, e.g. 'JBR, Dubai'. Shown on their public profile.", max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='field_tag',
            field=models.CharField(choices=[('tech', 'Tech'), ('design', 'Design'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('writing', 'Writing'), ('mixed', 'Mixed / general')], max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('request_received', 'Request received'), ('request_accepted', 'Request accepted'), ('request_declined', 'Request declined')], max_length=30)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='spaceshare.booking')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='spaceshare.listing')),
                ('user', models.ForeignKey(help_text='Recipient.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read'], name='spaceshare__user_id_656376_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField(blank=True)),
                ('direction', models.CharField(choices=[('host_to_guest', 'Host to guest'), ('guest_to_host', 'Guest to host')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='spaceshare.booking')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('booking', 'direction'), name='one_review_per_direction_per_booking'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_between_1_and_5')],
            },
        ),
    ]
